const state = { team: teams[0], driver: drivers[teams[0].drivers[0]], gp: calendar[0], lap: 1, pace: 1 };
const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => [...document.querySelectorAll(sel)];
function path(base, file){ return ASSETS[base] + file; }
function slugName(name){ return name.toLowerCase().replace(/\./g,'').replace(/ jr/g,'_jr').replace(/ /g,'_'); }
function show(screen){ $$('.screen').forEach(s => s.classList.remove('active')); const el = $('#screen-' + screen); if(el){ el.classList.add('active'); $('#miniRoute').textContent = el.dataset.screen || screen.toUpperCase(); } window.scrollTo(0,0); refresh(); }
function refresh(){ $('#miniBuild').textContent = `${BUILD.version} · ${BUILD.date} · ${BUILD.time}`; $('#footerBuild').textContent = `Build ${BUILD.version} · ${BUILD.date} · ${BUILD.time} · ${BUILD.label}`; updateHub(); updateRace(); }
function imgFallback(img){ img.onerror = () => { img.classList.add('missing'); img.removeAttribute('src'); }; }
function renderTeams(){ const grid = $('#teamGrid'); grid.innerHTML = ''; teams.forEach(team => { const card = document.createElement('button'); card.className = 'team-card'; card.style.setProperty('--team', team.color); card.innerHTML = `<img src="${path('teamCards', team.card)}" alt="${team.name}" /><div class="team-strip"><img src="${path('teamLogos', team.logo)}" alt="" /><div><strong>${team.name}</strong><small>${team.drivers.map(id=>drivers[id].name).join(' / ')}</small></div></div>`; card.onclick = () => { state.team = team; state.driver = drivers[team.drivers[0]]; renderDrivers(team); show('drivers'); }; grid.appendChild(card); card.querySelectorAll('img').forEach(imgFallback); }); }
function renderDrivers(team = state.team){ $('#driverTeamLabel').textContent = team.name; const grid = $('#driverGrid'); grid.innerHTML = ''; team.drivers.forEach(id => { const d = drivers[id]; const card = document.createElement('button'); card.className = 'driver-card'; card.style.setProperty('--team', team.color); card.innerHTML = `<img src="${path('drivers', d.img)}" alt="${d.name}" /><div class="driver-info"><span>#${d.num}</span><strong>${d.name}</strong><small>${team.name}</small></div>`; card.onclick = () => { state.driver = d; show('hub'); }; grid.appendChild(card); imgFallback(card.querySelector('img')); }); }
function updateHub(){ $('#hubTitle').textContent = `${state.team.name} Career`; $('#hubTeamName').textContent = state.team.name; $('#hubDriverName').textContent = `${state.driver.name} · #${state.driver.num}`; $('#hubTeamLogo').src = path('teamLogos', state.team.logo); }
function renderCalendar(){ const grid = $('#calendarGrid'); grid.innerHTML = ''; calendar.forEach(gp => { const card = document.createElement('button'); card.className = 'gp-card'; card.innerHTML = `<img class="gp-flag" src="${path('flags', gp.flag)}" alt="" /><img class="gp-track" src="${path('tracks', gp.track)}" alt="" /><div><span>R${String(gp.round).padStart(2,'0')}</span><strong>${gp.gp}</strong><small>${gp.laps} voltas · ${gp.night ? 'noturna' : 'diurna'}</small></div>`; card.onclick = () => { state.gp = gp; state.lap = 1; show('race'); }; grid.appendChild(card); card.querySelectorAll('img').forEach(imgFallback); }); }
function updateRace(){ const gp = state.gp; $('#raceBg').src = path('backgrounds', gp.night ? 'race_night.png' : 'race_day.png'); $('#raceFlag').src = path('flags', gp.flag); $('#raceTrack').src = path('tracks', gp.track); $('#raceRound').textContent = `R${String(gp.round).padStart(2,'0')}`; $('#raceName').textContent = gp.gp; $('#lapCounter').textContent = `${state.lap}/${gp.laps}`; $('#bestLap').textContent = `1:${String(28 + gp.round).padStart(2,'0')}.${842 - Math.min(gp.round*7, 400)}`; renderStandings(); }
function renderStandings(){ const ids = teams.flatMap(t => t.drivers.map(id => ({...drivers[id], team:t.name}))).slice(0,20); ids.sort((a,b)=> (a.name === state.driver.name ? -1 : b.name === state.driver.name ? 1 : a.num-b.num)); $('#liveStandings').innerHTML = ids.slice(0,10).map((d,i)=>`<li class="${d.name===state.driver.name?'selected':''}"><b>P${i+1}</b><span>${d.name.split(' ').slice(-1)[0]}</span><em>+${(i*1.37).toFixed(1)}s</em></li>`).join(''); }
function renderResults(){ const pool = teams.flatMap(t => t.drivers.map(id => ({...drivers[id], team:t.name, teamColor:t.color}))); pool.sort((a,b)=> a.name === state.driver.name ? -1 : b.name === state.driver.name ? 1 : a.num-b.num); $('#resultList').innerHTML = `<div class="result-title"><span>${state.gp.gp}</span><strong>Resultado</strong></div>` + pool.slice(0,10).map((d,i)=>`<div class="result-row"><b>${i+1}</b><span>${d.name}</span><em>${d.team}</em><strong>+${(i*3.8).toFixed(3)}</strong></div>`).join(''); $('#podiumDrivers').innerHTML = pool.slice(0,3).map((d,i)=>`<article><img src="${path('drivers', d.img)}" alt="${d.name}" /><b>P${i+1}</b><strong>${d.name}</strong><span>${d.team}</span></article>`).join(''); $('#podiumDrivers').querySelectorAll('img').forEach(imgFallback); }
function bind(){ document.body.addEventListener('click', e => { const go = e.target.closest('[data-go]'); if(go){ if(go.dataset.go === 'results' || go.dataset.go === 'podium') renderResults(); show(go.dataset.go); } }); $('#paceUp').onclick = () => { state.pace = Math.min(3, state.pace + 1); state.lap = Math.min(state.gp.laps, state.lap + 1); updateRace(); }; $('#paceDown').onclick = () => { state.pace = Math.max(0, state.pace - 1); state.lap = Math.min(state.gp.laps, state.lap + 1); updateRace(); }; $('#pitBtn').onclick = () => { state.lap = Math.min(state.gp.laps, state.lap + 1); updateRace(); }; $$('.screen-bg, img').forEach(imgFallback); }
renderTeams(); renderDrivers(); renderCalendar(); bind(); refresh();
