(function(){
  const BUILD='v0.28.0';
  const POINTS=[25,18,15,12,10,8,6,4,2,1];
  const FLAGS={'Austrália':'🇦🇺','China':'🇨🇳','Japão':'🇯🇵','Bahrein':'🇧🇭','Arábia Saudita':'🇸🇦','EUA':'🇺🇸','Mônaco':'🇲🇨','Canadá':'🇨🇦','Espanha':'🇪🇸','Áustria':'🇦🇹','Reino Unido':'🇬🇧','Bélgica':'🇧🇪','Hungria':'🇭🇺','Itália':'🇮🇹','Azerbaijão':'🇦🇿','Singapura':'🇸🇬','México':'🇲🇽','Brasil':'🇧🇷','Catar':'🇶🇦','Emirados Árabes':'🇦🇪'};
  const CAL=[['GP da Austrália','Austrália','Melbourne',58],['GP da China','China','Shanghai',56],['GP do Japão','Japão','Suzuka',53],['GP do Bahrein','Bahrein','Bahrain International Circuit',57],['GP da Arábia Saudita','Arábia Saudita','Jeddah',50],['GP de Miami','EUA','Miami',57],['GP de Mônaco','Mônaco','Monte Carlo',78],['GP do Canadá','Canadá','Gilles-Villeneuve',70],['GP da Espanha','Espanha','Barcelona-Catalunya',66],['GP da Áustria','Áustria','Red Bull Ring',71],['GP da Grã-Bretanha','Reino Unido','Silverstone',52],['GP da Hungria','Hungria','Hungaroring',70],['GP da Bélgica','Bélgica','Spa-Francorchamps',44],['GP da Itália','Itália','Monza',53],['GP do Azerbaijão','Azerbaijão','Baku',51],['GP de Singapura','Singapura','Marina Bay',62],['GP dos EUA','EUA','COTA',56],['GP do México','México','Hermanos Rodríguez',71],['GP do Brasil','Brasil','Interlagos',71],['GP do Catar','Catar','Lusail',57],['GP de Abu Dhabi','Emirados Árabes','Yas Marina',58]].map((r,i)=>({round:i+1,gp:r[0],country:r[1],track:r[2],laps:r[3]}));
  const SPONSORS=[['aramco','Aramco','Terminar com os dois carros',1800000,350000,'finish'],['pirelli','Pirelli','Pit obrigatório sem penalidade',1400000,300000,'clean'],['dhl','DHL','Pontuar com 1 piloto',1200000,250000,'points'],['lenovo','Lenovo','Top 10 duplo',2200000,500000,'double'],['crypto','Crypto.com','Pódio',4200000,900000,'podium'],['rolex','Rolex','Vitória',6000000,1300000,'win']].map(s=>({id:s[0],name:s[1],goal:s[2],bonus:s[3],penalty:s[4],type:s[5]}));
  function q(s){return document.querySelector(s)} function qa(s){return Array.from(document.querySelectorAll(s))}
  function S(){return window.STATE||(window.STATE={})} function T(){return Array.isArray(window.TEAMS)&&window.TEAMS.length?window.TEAMS:[]} function D(){return Array.isArray(window.DRIVERS)&&window.DRIVERS.length?window.DRIVERS:[]} function C(){if(!Array.isArray(window.CALENDAR)||!window.CALENDAR.length)window.CALENDAR=CAL;return window.CALENDAR}
  function money(v){return'R$ '+((v||0)/1000000).toFixed(1)+' mi'}
  function save(){try{S().stableBuild=BUILD;localStorage.setItem('f1_ve_save_slot_main_v0150',JSON.stringify({version:BUILD,savedAt:new Date().toISOString(),state:S()}));localStorage.setItem('f1_ve_visual_state',JSON.stringify(S()))}catch(e){}}
  function team(){const st=S();return T().find(t=>t.name===st.teamName||t.id===st.teamId||t.short===st.teamName)||T()[0]||{id:'mclaren',name:'McLaren',short:'McLaren',drivers:['Lando Norris','Oscar Piastri'],car:{power:88,aero:90,chassis:89,tyres:88,reliability:86},logo:'assets/teams/cards/logos/mclaren.png'}}
  function teamById(id){return T().find(t=>t.id===id)||team()} function logo(id){const t=teamById(id);return t.logo||('assets/teams/cards/logos/'+(t.id||id||'mclaren')+'.png')} function asset(d){return d.asset||('assets/drivers/'+String(d.name||'').toLowerCase().replaceAll(' ','_').replaceAll('.','')+'.png')}
  function normalize(){const st=S(),tm=team();st.money=typeof st.money==='number'?st.money:48750000;st.round=st.round||1;st.season=st.season||2026;st.teamName=st.teamName||tm.name;st.teamId=st.teamId||tm.id;st.avatar=st.avatar||'assets/avatar/avatar1.png';st.staff=st.staff||{technical:1,strategy:1,raceOps:1,commercial:1,mechanics:1};if(st.staff.mechanics===undefined)st.staff.mechanics=1;st.activeSponsors=Array.isArray(st.activeSponsors)&&st.activeSponsors.length?st.activeSponsors.slice(0,2):['aramco'];st.carParts=st.carParts||{};st.driverPoints=st.driverPoints||{};st.teamPoints=st.teamPoints||{};st.raceHistory=st.raceHistory||[];st.trophyRoom=st.trophyRoom||[];st.seasonStats=st.seasonStats||{races:0,wins:0,podiums:0,pointsFinishes:0,completedProjects:0};['power','aero','chassis','tyres','reliability'].forEach(k=>{if(typeof st.carParts[k]!=='number')st.carParts[k]=(tm.car&&tm.car[k])||78});if(!st.teamDrivers)st.teamDrivers={};if(!st.teamDrivers[tm.id])st.teamDrivers[tm.id]=(tm.drivers||[]).slice(0,2)}
  function selected(){normalize();const tm=team(),names=(S().teamDrivers&&S().teamDrivers[tm.id])||tm.drivers||[];let out=names.map(n=>D().find(d=>d.name===n)).filter(Boolean);if(out.length<2)out=D().filter(d=>d.teamId===tm.id).slice(0,2);return out} window.selectedDrivers=selected;
  function renderAgenda(){const box=q('#calendarList')||q('.calendar-list')||q('#agendaList'); if(!box)return; const r=S().round||1;box.innerHTML=C().map(x=>`<div class="calendar-row ${x.round===r?'current':''}"><b><span class="flag-emoji">${FLAGS[x.country]||'🏁'}</span> ${x.round}. ${x.gp}</b><span>${x.track} • ${x.laps} voltas</span></div>`).join('')}
  function renderSponsors(){const box=q('#sponsorPanel');if(!box)return;normalize();box.innerHTML=SPONSORS.map(s=>{const a=S().activeSponsors.includes(s.id);return`<div class="sponsor-contract ${a?'active':''}"><div class="sponsor-top"><b>${s.name}</b><span>${a?'ATIVO':'LIVRE'}</span></div><strong>${s.goal}</strong><p>Bônus ${money(s.bonus)} • Penalidade ${money(s.penalty)}</p><button data-v28-sponsor="${s.id}">${a?'REMOVER':'ASSINAR'}</button></div>`}).join('');qa('[data-v28-sponsor]').forEach(b=>b.onclick=e=>{e.preventDefault();const id=b.dataset.v28Sponsor;if(S().activeSponsors.includes(id)){if(S().activeSponsors.length<=1){alert('Mantenha pelo menos 1 patrocinador.');return}S().activeSponsors=S().activeSponsors.filter(x=>x!==id)}else{if(S().activeSponsors.length>=2){alert('Máximo 2 patrocinadores.');return}S().activeSponsors.push(id)}save();renderSponsors()})}
  function renderWorkshop(){const parts=q('#carPartsPanel'),projects=q('#carProjectsPanel')||q('#developmentPackages');normalize();const names={power:'Motor',aero:'Aerodinâmica',chassis:'Chassi',tyres:'Pneus',reliability:'Confiabilidade'};if(parts)parts.innerHTML=Object.keys(names).map(k=>`<div class="car-part-card"><b>${names[k]}</b><strong>${S().carParts[k]}</strong><span>Impacto direto na corrida.</span><i><em style="width:${S().carParts[k]}%"></em></i></div>`).join('');if(projects){const dev=[['power','Motor',2,5200000],['aero','Aerodinâmica',3,8200000],['chassis','Chassi',2,6100000],['tyres','Pneus',3,4700000],['reliability','Confiabilidade',3,4300000]];projects.innerHTML=dev.map(p=>`<div class="project-card"><b>Desenvolver ${p[1]}</b><span>+${p[2]} desempenho</span><small>${money(p[3])}</small><button data-v28-dev="${p[0]}" data-cost="${p[3]}" data-boost="${p[2]}">DESENVOLVER</button></div>`).join('');qa('[data-v28-dev]').forEach(b=>b.onclick=()=>{const cost=+b.dataset.cost;if(S().money<cost){alert('Caixa insuficiente.');return}S().money-=cost;S().carParts[b.dataset.v28Dev]=Math.min(99,(S().carParts[b.dataset.v28Dev]||75)+(+b.dataset.boost));S().seasonStats.completedProjects++;save();renderWorkshop();renderDashboard()})}}
  function race(){return C()[(S().round||1)-1]||C()[0]} function buildGrid(){const tm=team(),sel=selected();let g=D().map((d,i)=>({id:d.id,name:d.name,flag:d.flag||'',team:d.team||teamById(d.teamId).short||'',teamId:d.teamId||'',asset:asset(d),number:d.number||'',pos:i+1,tyreLife:100,pitted:false,out:false,compound:'Médio'}));sel.forEach((d,i)=>{let x=g.find(y=>y.id===d.id);if(x){x.teamId=tm.id;x.team=tm.short||tm.name;x.pos=i+7}});g.sort((a,b)=>a.pos-b.pos).forEach((d,i)=>d.pos=i+1);return g}
  function ensureRaceUI(){const scr=q('#screenRace');if(!scr)return;let box=q('#stableRaceControls');if(!box){box=document.createElement('div');box.id='stableRaceControls';box.className='stable-race-controls';scr.insertBefore(box,q('#liveGrid')||q('.live-grid')||null)}let btn=q('#startRaceBtn')||qa('#screenRace button').find(b=>(b.textContent||'').toLowerCase().includes('iniciar corrida'));if(!btn){btn=document.createElement('button');btn.id='startRaceBtn';btn.className='cta compact';btn.textContent='INICIAR CORRIDA';scr.insertBefore(btn,box)}btn.onclick=e=>{e.preventDefault();startRace()}}
  function startRace(){normalize();let r=race();S().liveRace={running:true,paused:false,finished:false,settled:false,lap:0,totalLaps:r.laps,raceName:r.gp,grid:buildGrid(),speed:1,commentary:['Largada autorizada.'],radio:['Engenheiro: corrida iniciada. Escolha o momento do pit.']};restart();renderRace();save()} window.startLiveRace=startRace;
  function restart(){if(window._v28Timer)clearInterval(window._v28Timer);window._v28Timer=setInterval(tick,Math.max(260,1200/((S().liveRace&&S().liveRace.speed)||1)))}
  function tick(){let l=S().liveRace;if(!l||!l.running||l.paused||l.finished)return;l.lap++;l.grid.forEach(d=>{if(d.out)return;let loss=d.compound==='Macio'?1.25:d.compound==='Duro'?0.65:.9;d.tyreLife=Math.max(0,d.tyreLife-(d.pitted?loss*.72:loss));if(Math.random()<.16+((100-d.tyreLife)/900))d.pos=Math.max(1,Math.min(l.grid.length,d.pos+(Math.random()<.5?-1:1)));});l.grid.sort((a,b)=>a.pos-b.pos).forEach((d,i)=>{if(!d.out)d.pos=i+1});if(l.lap%3===0)l.commentary.unshift('Volta '+l.lap+': ritmo forte e disputa por posição.');selected().forEach(d=>{let x=l.grid.find(y=>y.id===d.id);if(x&&!x.pitted&&x.tyreLife<42&&l.radio.length<14)l.radio.unshift(x.name+': pneus acabando, podemos parar?')});if(l.lap>=l.totalLaps){l.finished=true;l.running=false;clearInterval(window._v28Timer);finishRace()}renderRace();save()}
  function pit(id,comp){let l=S().liveRace;if(!l||l.finished)return;let d=l.grid.find(x=>x.id===id);if(!d)return;d.pitted=true;d.compound=comp;d.tyreLife=100;let loss=2+Math.max(0,4-(S().staff.mechanics||1));d.pos=Math.min(l.grid.length,d.pos+loss);l.radio.unshift('Box: '+d.name+' fez pit para '+comp+'.');l.commentary.unshift('Volta '+l.lap+': '+d.name+' vai aos boxes.');l.grid.sort((a,b)=>a.pos-b.pos).forEach((x,i)=>x.pos=i+1);renderRace();save()}
  function finishRace(){let l=S().liveRace;if(!l||l.settled)return;l.settled=true;l.podium=l.grid.slice().sort((a,b)=>a.pos-b.pos).slice(0,3);l.commentary.unshift('Bandeirada final: '+l.podium[0].name+' vence '+l.raceName+'.');applyPoints(l.grid.slice().sort((a,b)=>a.pos-b.pos));settleSponsors(l.grid.slice().sort((a,b)=>a.pos-b.pos));S().round=(S().round||1)+1;save();renderPodium();if(window.showScreen)window.showScreen('screenStablePodium')}
  function applyPoints(sorted){sorted.slice(0,10).forEach((d,i)=>{let pts=POINTS[i]||0;S().driverPoints[d.id]=(S().driverPoints[d.id]||0)+pts;S().teamPoints[d.teamId]=(S().teamPoints[d.teamId]||0)+pts});let ids=selected().map(d=>d.id),best=sorted.filter(d=>ids.includes(d.id)).sort((a,b)=>a.pos-b.pos)[0];if(best){S().seasonStats.races++;if(best.pos===1)S().seasonStats.wins++;if(best.pos<=3)S().seasonStats.podiums++;if(best.pos<=10)S().seasonStats.pointsFinishes++;S().raceHistory.unshift({gp:S().liveRace.raceName,best:best.pos,season:S().season,date:new Date().toLocaleDateString('pt-BR')})}}
  function sponsorOK(s,sorted){let ids=selected().map(d=>d.id),u=sorted.filter(d=>ids.includes(d.id));if(s.type==='finish')return u.every(d=>!d.out);if(s.type==='clean')return u.every(d=>d.pitted&&!d.out);if(s.type==='points')return u.some(d=>d.pos<=10&&!d.out);if(s.type==='double')return u.every(d=>d.pos<=10&&!d.out);if(s.type==='podium')return u.some(d=>d.pos<=3&&!d.out);if(s.type==='win')return u.some(d=>d.pos===1&&!d.out);return false}
  function settleSponsors(sorted){S().lastSponsorSettlement=[];S().activeSponsors.forEach(id=>{let s=SPONSORS.find(x=>x.id===id);if(!s)return;let ok=sponsorOK(s,sorted),val=ok?s.bonus:-s.penalty;S().money+=val;S().lastSponsorSettlement.push({name:s.name,ok,value:val})})}
  function renderControls(){const box=q('#stableRaceControls'),l=S().liveRace;if(!box)return;const ds=selected();box.innerHTML=`<div class="stable-control-row"><button data-speed="1">1x</button><button data-speed="2">2x</button><button data-speed="4">4x</button><button data-pause>${l&&l.paused?'RETOMAR':'PAUSAR'}</button></div><div class="stable-pit-row">${ds.map(d=>`<div><b>${d.flag||''} ${d.name}</b><button data-pit="${d.id}" data-comp="Macio">Pit Macio</button><button data-pit="${d.id}" data-comp="Médio">Pit Médio</button><button data-pit="${d.id}" data-comp="Duro">Pit Duro</button></div>`).join('')}</div>`;qa('[data-speed]').forEach(b=>b.onclick=()=>{if(S().liveRace){S().liveRace.speed=+b.dataset.speed;restart();renderRace()}});qa('[data-pause]').forEach(b=>b.onclick=()=>{if(S().liveRace){S().liveRace.paused=!S().liveRace.paused;renderRace();save()}});qa('[data-pit]').forEach(b=>b.onclick=()=>pit(b.dataset.pit,b.dataset.comp))}
  function renderRace(){ensureRaceUI();const r=race(),l=S().liveRace,p=q('#screenRace p');if(p)p.textContent=`${r.gp} • ${r.track} • ${r.laps} voltas`;renderControls();qa('#screenRace strong,#screenRace .stat-card strong,#screenRace .race-stat strong').forEach(el=>{let tx=(el.textContent||'').trim();if(/^\d+\s*\/\s*\d+$/.test(tx)&&l)el.textContent=`${l.lap||0} / ${l.totalLaps||r.laps}`;if(['Pré-corrida','Em andamento','Finalizada','Pausada'].includes(tx))el.textContent=l?(l.finished?'Finalizada':l.paused?'Pausada':'Em andamento'):'Pré-corrida'});let grid=q('#liveGrid')||q('#raceGrid')||q('.live-grid')||qa('#screenRace .panel,#screenRace .card').find(x=>(x.textContent||'').includes('GRID'));if(grid&&l)grid.innerHTML='<h3>GRID AO VIVO</h3>'+l.grid.slice().sort((a,b)=>a.pos-b.pos).slice(0,20).map(d=>`<div class="race-row-stable"><b>P${d.pos}</b><img src="${asset(d)}" onerror="this.style.display=\'none\'"><span><strong>${d.flag||''} ${d.name}</strong><small>${d.team||''} • ${d.compound||'Médio'} • pneu ${Math.round(d.tyreLife||0)}%</small></span><img class="logo" src="${logo(d.teamId)}" onerror="this.style.display=\'none\'"></div>`).join('');let comm=q('#liveCommentary')||q('#raceCommentary')||q('.commentary')||qa('#screenRace .panel,#screenRace .card').find(x=>(x.textContent||'').includes('NARRAÇÃO'));if(comm&&l)comm.innerHTML='<h3>NARRAÇÃO AO VIVO</h3>'+l.commentary.slice(0,8).map(x=>'<p>'+x+'</p>').join('')+'<h3>RÁDIO</h3>'+l.radio.slice(0,5).map(x=>'<p>'+x+'</p>').join('')}
  function renderPodium(){const box=q('#stablePodiumPanel');if(!box||!S().liveRace||!S().liveRace.podium)return;let p=S().liveRace.podium;box.innerHTML='<div class="podium-grid-stable">'+p.map((d,i)=>`<div class="podium-card-stable pos${i+1}"><img class="driver" src="${asset(d)}" onerror="this.style.display=\'none\'"><b>${i+1}º</b><strong>${d.flag||''} ${d.name}</strong><span>${d.team}</span><img class="team" src="${logo(d.teamId)}" onerror="this.style.display=\'none\'"></div>`).join('')+'</div><div class="podium-summary-stable"><b>Patrocínios</b>'+((S().lastSponsorSettlement||[]).map(x=>`<p>${x.name}: ${x.ok?'bônus':'penalidade'} ${money(Math.abs(x.value))}</p>`).join('')||'<p>Sem contratos liquidados.</p>')+'</div><button class="cta compact" data-goto="screenLobby">VOLTAR AO LOBBY</button>'}
  function renderDashboard(){let b=q('#managerDashboardPanel');if(b)b.innerHTML=`<div class="board-card main"><b>${team().short||team().name}</b><strong>${money(S().money)}</strong><span>Carro ${Math.round(['power','aero','chassis','tyres','reliability'].map(k=>S().carParts[k]||75).reduce((a,b)=>a+b,0)/5)} • temporada ${S().season}</span></div>`;let s=q('#seasonHubPanel');if(s)s.innerHTML=`<div class="season-card main"><b>Temporada ${S().season}</b><strong>${S().round}</strong><span>Rodada atual</span></div><div class="season-grid"><div class="season-card"><b>Corridas</b><strong>${S().seasonStats.races}</strong></div><div class="season-card"><b>Vitórias</b><strong>${S().seasonStats.wins}</strong></div><div class="season-card"><b>Pódios</b><strong>${S().seasonStats.podiums}</strong></div><div class="season-card"><b>Top 10</b><strong>${S().seasonStats.pointsFinishes}</strong></div></div>`}
  function attachNav(){qa('[data-goto]').forEach(b=>{b.onclick=e=>{e.preventDefault();if(window.showScreen)window.showScreen(b.dataset.goto);else{qa('.screen').forEach(x=>x.classList.remove('active'));let el=q('#'+b.dataset.goto);if(el)el.classList.add('active')}setTimeout(renderAll,80)}})}
  function renderAll(){normalize();attachNav();renderAgenda();renderSponsors();renderWorkshop();ensureRaceUI();renderRace();renderPodium();renderDashboard();save()} window.renderLiveRace=renderRace; window.v0280StableRender=renderAll;
  document.addEventListener('DOMContentLoaded',()=>setTimeout(renderAll,500)); window.addEventListener('load',()=>setTimeout(renderAll,900)); document.addEventListener('click',e=>{if(e.target.closest('[data-goto]'))setTimeout(renderAll,120)});
})();
